# Generated by Django 4.0.6 on 2022-08-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_individual', models.IntegerField()),
                ('reponer', models.IntegerField()),
                ('observacion', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_individual', models.IntegerField()),
                ('reponer', models.IntegerField()),
                ('observacion', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_individual', models.IntegerField()),
                ('reponer', models.IntegerField()),
                ('observacion', models.CharField(max_length=10000)),
            ],
        ),
    ]
