# Generated by Django 4.0.6 on 2022-08-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negocio_1',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Negocio 1'},
        ),
        migrations.AlterModelOptions(
            name='negocio_2',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Negocio 2'},
        ),
        migrations.AlterModelOptions(
            name='negocio_3',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Negocio 3'},
        ),
    ]
