# Generated by Django 4.1 on 2022-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_negocio_1_options_alter_negocio_2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio_1',
            name='hora_cargado',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='negocio_2',
            name='hora_cargado',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='negocio_3',
            name='hora_cargado',
            field=models.CharField(default='', max_length=20),
        ),
    ]
