# Generated by Django 4.1 on 2022-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_negocio_3_hora_cargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio_1',
            name='hora_cargado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='negocio_2',
            name='hora_cargado',
            field=models.CharField(max_length=20),
        ),
    ]
