# Generated by Django 4.0.6 on 2022-08-28 01:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_negocio_1_hora_cargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio_1',
            name='observacion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
