# Generated by Django 4.0.6 on 2022-08-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_negocio_1_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio_1',
            name='observacion',
            field=models.CharField(max_length=10000),
        ),
    ]
