# Generated by Django 4.0.6 on 2022-08-28 01:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
