# Generated by Django 4.0.6 on 2022-08-28 01:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
