# Generated by Django 4.0.6 on 2022-08-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='descripcion',
        ),
    ]
