# Generated by Django 4.0.6 on 2022-08-29 23:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
