# Generated by Django 4.0.6 on 2022-08-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sitio_link',
            field=models.URLField(blank=True, max_length=155),
        ),
    ]
