# Generated by Django 4.0.6 on 2022-08-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=10000)),
                ('usuario', models.CharField(max_length=10000)),
                ('hora_enviado', models.DateTimeField()),
            ],
        ),
    ]
